"""Add crop flag to technology

Revision ID: 6d5ca50916f4
Revises: 8f9c1f3f2153
Create Date: 2021-10-07 15:24:50.806500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6d5ca50916f4"
down_revision = "8f9c1f3f2153"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enumerator",
        "enum_active",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "prjcombination",
        "comb_usable",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "prjlang",
        "lang_default",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "project",
        "project_active",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'1'"),
    )
    op.alter_column(
        "project",
        "project_public",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "question",
        "question_optperprj",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "question",
        "question_reqinasses",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "question",
        "question_reqinreg",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.add_column(
        "technology",
        sa.Column(
            "tech_crop", sa.Integer(), server_default=sa.text("'0'"), nullable=True
        ),
    )
    op.alter_column(
        "user",
        "user_active",
        existing_type=mysql.TINYINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'1'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "user_active",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'1'"),
    )
    op.drop_column("technology", "tech_crop")
    op.alter_column(
        "question",
        "question_reqinreg",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "question",
        "question_reqinasses",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "question",
        "question_optperprj",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "project",
        "project_public",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "project",
        "project_active",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'1'"),
    )
    op.alter_column(
        "prjlang",
        "lang_default",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "prjcombination",
        "comb_usable",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "enumerator",
        "enum_active",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
